global:
  scrape_interval:     1s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cadvisor'
    scrape_interval: 1s
    static_configs:
      - targets: ['10.210.154.234:8080']